### PR TITLE
	makes NumericalInputDialog compatible with multicharset locales:   u…

### PR DESCRIPTION
**Pull request by lprot**
…sr/share/enigma2/PLi-HD/skin.xml

If you select locales like Russian, Ukrainian etc which have two charsets active at the same time you get characters cut at the dialog window. The PR fixes that.

### CODE REVIEW

**Comment by ims21** [comment]
Font size 16 is very small ...

**Comment by lprot** [comment]
[https://preview.ibb.co/nMYbBx/1_0_19_1_E0_A_2_B_55_300000_0_0_0_20180428114127.jpg" alt="1_0_19_1_E0_A_2_B_55_300000_0_0_0_20180428114127"](url)

**Comment by ims21** [comment]
But other languages must use smaller texts ... better would be use 2 version, imho ...

**Comment by ims21** [comment]
Will be fixed in e2 code as "autoresize" font for this screen...

**Comment by lprot** [comment]
That's nice. Probably you can get rid of that old fashioned keyboard at all and force using of virtual one?

**Comment by ims21** [comment]
You can always toggle to virtual keyboard with Text button...

**Comment by ims21** [comment]
solved in developed code yet

**Pull request closed without merging**
