### PR TITLE
Screen has a menu key action

### PR DESCRIPTION
**Pull request by talbss**

### CODE REVIEW

**Comment by eriksl** [comment]
Please explain.

**Comment by talbss** [comment]
Pressing thé menu key on the remote shows thé log. 
Si modiffying thé associates skin to display the "menu" picture on thé bottom left.

**Comment by talbss** [comment]
do i need to explain a little bit more?

**Comment by eriksl** [comment]
Just to be sure. At some point the user can press the "menu" buttom. Your patch shows in the skin that the menu button can be pressed at that point. Right?

**Comment by talbss** [comment]
Right!

**Pull request merged**
